In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
import pandas as pd

In [4]:
file_path = '/content/drive/MyDrive/Road_Accident_Aalysis_project/US_Accidents_March23.csv'

In [5]:
df = pd.read_csv(file_path, nrows=100000)
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 46 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     100000 non-null  object
 1   Source                 100000 non-null  object
 2   Severity               100000 non-null  int64
 3   Start_Time             100000 non-null  object
 4   End_Time               100000 non-null  object
 5   Start_Lat              100000 non-null  float64
 6   Start_Lng              100000 non-null  float64
 7   End_Lat                0 non-null       float64
 8   End_Lng                0 non-null       float64
 9   Distance(mi)           100000 non-null  float64
 10  Description            100000 non-null  object
 11  Street                 100000 non-null  object
 12  City                   99999 non-null   object
 13  County                 100000 non-null  object
 14  State                  100000 non-null  object
 15  Zipcode                99993 non-null   object
 16  Country                100000 non-null  object
 17  Timezone               99993 non-null   object
 18  Airport_Code           99993 non-null   object
 19  Weather_Timestamp      98946 non-null   object
 20  Temperature(F)         98409 non-null   float64
 21  Wind_Chill(F)          4322 non-null    float64
 22  Humidity(%)            98144 non-null   float64
 23  Pressure(in)           98708 non-null   float64
 24  Visibility(mi)         98154 non-null   float64
 25  Wind_Direction         98936 non-null   object
 26  Wind_Speed(mph)        76180 non-null   float64
 27  Precipitation(in)      7368 non-null    float64
 28  Weather_Condition      98396 non-null   object
 29  Amenity                100000 non-null  bool
 30  Bump                   100000 non-null  bool
 31  Crossing               100000 non-null  bool
 32  Give_Way               100000 non-null  bool
 33  Junction               100000 non-null  bool
 34  No_Exit                100000 non-null  bool
 35  Railway                100000 non-null  bool
 36  Roundabout             100000 non-null  bool
 37  Station                100000 non-null  bool
 38  Stop                   100000 non-null  bool
 39  Traffic_Calming        100000 non-null  bool
 40  Traffic_Signal         100000 non-null  bool
 41  Turning_Loop           100000 non-null  bool
 42  Sunrise_Sunset         99999 non-null   object
 43  Civil_Twilight         99999 non-null   object
 44  Nautical_Twilight      99999 non-null   object
 45  Astronomical_Twilight  99999 non-null   object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 26.4+ MB

In [7]:
(df.isnull().sum() / df.shape[0])*100

ID                         0.000
Source                     0.000
Severity                   0.000
Start_Time                 0.000
End_Time                   0.000
Start_Lat                  0.000
Start_Lng                  0.000
End_Lat                  100.000
End_Lng                  100.000
Distance(mi)               0.000
Description                0.000
Street                     0.000
City                       0.001
County                     0.000
State                      0.000
Zipcode                    0.007
Country                    0.000
Timezone                   0.007
Airport_Code               0.007
Weather_Timestamp          1.054
Temperature(F)             1.591
Wind_Chill(F)             95.678
Humidity(%)                1.856
Pressure(in)               1.292
Visibility(mi)             1.846
Wind_Direction             1.064
Wind_Speed(mph)           23.820
Precipitation(in)         92.632
Weather_Condition          1.604
Amenity                    0.000
Bump                       0.000
Crossing                   0.000
Give_Way                   0.000
Junction                   0.000
No_Exit                    0.000
Railway                    0.000
Roundabout                 0.000
Station                    0.000
Stop                       0.000
Traffic_Calming            0.000
Traffic_Signal             0.000
Turning_Loop               0.000
Sunrise_Sunset             0.001
Civil_Twilight             0.001
Nautical_Twilight          0.001
Astronomical_Twilight      0.001
dtype: float64

In [8]:
# no of cloumns
df.columns

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description',
       'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [9]:
# Drop the columns of 'End_Lat', 'End_Lng'
df = df.drop(columns=['End_Lat', 'End_Lng'])

In [10]:
# Without datetime, Start_Time and End_Time are just strings, and subtraction wouldn’t work.
# Convert the 'Start_Time' and 'End_Time' columns to datetime format
df['Start_Time'] = pd.to_datetime(df['Start_Time'], format='mixed')
df['End_Time'] = pd.to_datetime(df['End_Time'], format='mixed')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 44 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     100000 non-null  object
 1   Source                 100000 non-null  object
 2   Severity               100000 non-null  int64
 3   Start_Time             100000 non-null  datetime64[ns]
 4   End_Time               100000 non-null  datetime64[ns]
 5   Start_Lat              100000 non-null  float64
 6   Start_Lng              100000 non-null  float64
 7   Distance(mi)           100000 non-null  float64
 8   Description            100000 non-null  object
 9   Street                 100000 non-null  object
 10  City                   99999 non-null   object
 11  County                 100000 non-null  object
 12  State                  100000 non-null  object
 13  Zipcode                99993 non-null   object
 14  Country                100000 non-null  object
 15  Timezone               99993 non-null   object
 16  Airport_Code           99993 non-null   object
 17  Weather_Timestamp      98946 non-null   object
 18  Temperature(F)         98409 non-null   float64
 19  Wind_Chill(F)          4322 non-null    float64
 20  Humidity(%)            98144 non-null   float64
 21  Pressure(in)           98708 non-null   float64
 22  Visibility(mi)         98154 non-null   float64
 23  Wind_Direction         98936 non-null   object
 24  Wind_Speed(mph)        76180 non-null   float64
 25  Precipitation(in)      7368 non-null    float64
 26  Weather_Condition      98396 non-null   object
 27  Amenity                100000 non-null  bool
 28  Bump                   100000 non-null  bool
 29  Crossing               100000 non-null  bool
 30  Give_Way               100000 non-null  bool
 31  Junction               100000 non-null  bool
 32  No_Exit                100000 non-null  bool
 33  Railway                100000 non-null  bool
 34  Roundabout             100000 non-null  bool
 35  Station                100000 non-null  bool
 36  Stop                   100000 non-null  bool
 37  Traffic_Calming        100000 non-null  bool
 38  Traffic_Signal         100000 non-null  bool
 39  Turning_Loop           100000 non-null  bool
 40  Sunrise_Sunset         99999 non-null   object
 41  Civil_Twilight         99999 non-null   object
 42  Nautical_Twilight      99999 non-null   object
 43  Astronomical_Twilight  99999 non-null   object
dtypes: bool(13), datetime64[ns](2), float64(10), int64(1), object(18)
memory usage: 24.9+ MB

In [11]:
# Convert coordinates to numeric (if not already)
#because of Strings or objects cannot be used in mathematical formulas.
df['Start_Lat'] = pd.to_numeric(df['Start_Lat'], errors='coerce')
df['Start_Lng'] = pd.to_numeric(df['Start_Lng'], errors='coerce')

In [12]:
(df.isnull().sum() / df.shape[0])*100

ID                        0.000
Source                    0.000
Severity                  0.000
Start_Time                0.000
End_Time                  0.000
Start_Lat                 0.000
Start_Lng                 0.000
Distance(mi)              0.000
Description               0.000
Street                    0.000
City                      0.001
County                    0.000
State                     0.000
Zipcode                   0.007
Country                   0.000
Timezone                  0.007
Airport_Code              0.007
Weather_Timestamp         1.054
Temperature(F)            1.591
Wind_Chill(F)            95.678
Humidity(%)               1.856
Pressure(in)              1.292
Visibility(mi)            1.846
Wind_Direction            1.064
Wind_Speed(mph)          23.820
Precipitation(in)        92.632
Weather_Condition         1.604
Amenity                   0.000
Bump                      0.000
Crossing                  0.000
Give_Way                  0.000
Junction                  0.000
No_Exit                   0.000
Railway                   0.000
Roundabout                0.000
Station                   0.000
Stop                      0.000
Traffic_Calming           0.000
Traffic_Signal            0.000
Turning_Loop              0.000
Sunrise_Sunset            0.001
Civil_Twilight            0.001
Nautical_Twilight         0.001
Astronomical_Twilight     0.001
dtype: float64

In [13]:
df.columns

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'Distance(mi)', 'Description', 'Street', 'City', 'County',
       'State', 'Zipcode', 'Country', 'Timezone', 'Airport_Code',
       'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)',
       'Pressure(in)', 'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [14]:
# Drop the rows with missing values except some columns.
df = df.dropna(subset=['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'Distance(mi)', 'Description', 'Street', 'City', 'County',
       'State', 'Zipcode', 'Country', 'Timezone', 'Airport_Code',
       'Weather_Timestamp', 'Temperature(F)', 'Humidity(%)',
       'Pressure(in)', 'Visibility(mi)', 'Wind_Direction','Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'])

In [ ]:
(df.isnull().sum() / df.shape[0])*100

ID                        0.000000
Source                    0.000000
Severity                  0.000000
Start_Time                0.000000
End_Time                  0.000000
Start_Lat                 0.000000
Start_Lng                 0.000000
Distance(mi)              0.000000
Description               0.000000
Street                    0.000000
City                      0.000000
County                    0.000000
State                     0.000000
Zipcode                   0.000000
Country                   0.000000
Timezone                  0.000000
Airport_Code              0.000000
Weather_Timestamp         0.000000
Temperature(F)            0.000000
Wind_Chill(F)            23.854236
Humidity(%)               0.000000
Pressure(in)              0.000000
Visibility(mi)            0.000000
Wind_Direction            0.000000
Wind_Speed(mph)           5.089997
Precipitation(in)        27.520515
Weather_Condition         0.000000
Amenity                   0.000000
Bump                      0.000000
Crossing                  0.000000
Give_Way                  0.000000
Junction                  0.000000
No_Exit                   0.000000
Railway                   0.000000
Roundabout                0.000000
Station                   0.000000
Stop                      0.000000
Traffic_Calming           0.000000
Traffic_Signal            0.000000
Turning_Loop              0.000000
Sunrise_Sunset            0.000000
Civil_Twilight            0.000000
Nautical_Twilight         0.000000
Astronomical_Twilight     0.000000
dtype: float64

### Task: Impute the columns ['Wind_Speed(mph)', 'Precipitation(in)','Wind_Chill(F)'] with suitable imputation technique.

In [15]:
df[['Wind_Chill(F)', 'Wind_Speed(mph)', 'Precipitation(in)']].sample(5)

       Wind_Chill(F)  Wind_Speed(mph)  Precipitation(in)
16713            NaN              NaN                NaN
32999            NaN             11.5                NaN
31020            NaN              6.9                NaN
76748            NaN              NaN                NaN
97644            NaN              NaN                NaN

In [16]:
(df[['Wind_Chill(F)', 'Wind_Speed(mph)', 'Precipitation(in)']].isnull().sum())/df.shape[0]*100

Wind_Chill(F)        95.612443
Wind_Speed(mph)      22.728867
Precipitation(in)    92.598705
dtype: float64

In [17]:
# Median imputation for Wind_Speed(mph)
wind_median = df['Wind_Speed(mph)'].median()
df['Wind_Speed(mph)'] = df['Wind_Speed(mph)'].fillna(wind_median)

# Primary imputation for Precipitation(in): zero-fill
df['Precipitation(in)'] = df['Precipitation(in)'].fillna(0.0)

# Secondary imputation for known rain days: fill remaining gaps with median of nonzero precipitation
median_nonzero_precip = df.loc[df['Precipitation(in)'] > 0, 'Precipitation(in)'].median()

# Example mask for known rain days (replace with your actual condition)
# e.g., df['Rain_Flag'] == 1 or based on another indicator column
rain_day_mask = df['Precipitation(in)'].isna()  # placeholder if original missing flags retained

# Apply secondary imputation
df.loc[rain_day_mask, 'Precipitation(in)'] = median_nonzero_precip

In [18]:
from sklearn.linear_model import LinearRegression

# Select features to predict Wind_Chill(F)
reg_features = ['Wind_Speed(mph)', 'Temperature(F)', 'Humidity(%)']  # adjust to available predictors

# Split known and unknown
known_wc = df[df['Wind_Chill(F)'].notna()]
unknown_wc = df[df['Wind_Chill(F)'].isna()]

# Train regression model
X_train = known_wc[reg_features]
y_train = known_wc['Wind_Chill(F)']
reg = LinearRegression()
reg.fit(X_train, y_train)

# Predict missing Wind_Chill(F)
X_pred = unknown_wc[reg_features]
predicted_wc = reg.predict(X_pred)

# Impute missing values
df.loc[df['Wind_Chill(F)'].isna(), 'Wind_Chill(F)'] = predicted_wc

In [19]:
(df[['Wind_Chill(F)', 'Wind_Speed(mph)', 'Precipitation(in)']].isnull().sum())/df.shape[0]*100

Wind_Chill(F)        0.0
Wind_Speed(mph)      0.0
Precipitation(in)    0.0
dtype: float64

In [20]:
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Street,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,0.01,Right lane blocked due to accident on I-70 Eas...,I-70 E,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,0.01,Accident on Brice Rd at Tussing Rd. Expect del...,Brice Rd,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.01,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.01,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,...,False,False,False,False,True,False,Day,Day,Day,Day